site_name: Torch Choice
site_url: https://example.com/
docs_dir: docs_src
site_dir: docs
nav:
    - Home: index.md
    - Installation: install.md
    - Introduction: intro.md
    - Tutorial for Data Management: data_management.md
    - Tutorial for Easy Data Management and Stata Users: easy_data_management.md
    - Tutorial for Conditional Logit Model: conditional_logit_model_mode_canada.md
    - Tutorial for Nested Logit Model: nested_logit_model_house_cooling.md
    - Related Projects: projects.md
    - Compatibility Tests: test.md
    - API Reference Torch-Choice: api_torch_choice.md

# theme: readthedocs
theme:
    name: material
    custom_dir: docs_src/overrides
    icon:
        logo: stanford/stanford

plugins:
    - search
    - mkdocstrings

markdown_extensions:
#   - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs_src/overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML
